use crate::util::private_ip::is_ip_private;

/// Read nameserver entries from /etc/resolv.conf, masking private IPs as "private".
/// Mirrors getDnsServers() in src/lib/dns.ts.
pub fn get_dns_servers() -> Vec<String> {
    let content = std::fs::read_to_string("/etc/resolv.conf").unwrap_or_default();
    parse_resolv_conf(&content)
}

pub fn parse_resolv_conf(content: &str) -> Vec<String> {
    content
        .lines()
        .filter_map(|line| {
            let line = line.trim();
            let ip = line.strip_prefix("nameserver")?.trim();
            // Strip any trailing port (e.g. "8.8.8.8#53" or "[::1]:53")
            let ip = ip
                .trim_start_matches('[')
                .split(|c| c == ']' || c == '#')
                .next()
                .unwrap_or(ip)
                .trim();
            if ip.is_empty() { return None; }
            // Mask private IPs
            if let Ok(addr) = ip.parse() {
                if is_ip_private(addr) {
                    return Some("private".to_string());
                }
            }
            Some(ip.to_string())
        })
        .collect()
}

// ── Unit tests ────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_public_nameservers() {
        let conf = "# Generated by NetworkManager\nnameserver 8.8.8.8\nnameserver 1.1.1.1\n";
        let servers = parse_resolv_conf(conf);
        assert_eq!(servers, vec!["8.8.8.8", "1.1.1.1"]);
    }

    #[test]
    fn masks_private_nameservers() {
        let conf = "nameserver 192.168.1.1\nnameserver 8.8.8.8\n";
        let servers = parse_resolv_conf(conf);
        assert_eq!(servers, vec!["private", "8.8.8.8"]);
    }

    #[test]
    fn masks_loopback_nameserver() {
        let conf = "nameserver 127.0.0.53\n";
        let servers = parse_resolv_conf(conf);
        assert_eq!(servers, vec!["private"]);
    }

    #[test]
    fn skips_comment_and_option_lines() {
        let conf = "# comment\nsearch example.com\noptions ndots:5\nnameserver 9.9.9.9\n";
        let servers = parse_resolv_conf(conf);
        assert_eq!(servers, vec!["9.9.9.9"]);
    }

    #[test]
    fn handles_ipv6_nameserver() {
        let conf = "nameserver 2606:4700:4700::1111\n";
        let servers = parse_resolv_conf(conf);
        assert_eq!(servers, vec!["2606:4700:4700::1111"]);
    }

    #[test]
    fn masks_private_ipv6() {
        let conf = "nameserver ::1\nnameserver 2606:4700:4700::1111\n";
        let servers = parse_resolv_conf(conf);
        assert_eq!(servers, vec!["private", "2606:4700:4700::1111"]);
    }

    #[test]
    fn empty_resolv_conf_returns_empty_list() {
        assert!(parse_resolv_conf("").is_empty());
    }

    #[test]
    fn strips_port_number_from_nameserver() {
        let conf = "nameserver 8.8.8.8#53\n";
        let servers = parse_resolv_conf(conf);
        assert_eq!(servers, vec!["8.8.8.8"]);
    }

    #[cfg(target_os = "linux")]
    #[test]
    fn live_reads_resolv_conf() {
        let servers = get_dns_servers();
        println!("DNS servers: {servers:?}");
        // Should have at least one entry in a working Linux system
        // (could be empty in minimal containers, so don't assert non-empty)
    }
}
